//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessWatcher {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessWatcher.Resources.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AutoRestart.
        /// </summary>
        public static string AutoRestart {
            get {
                return ResourceManager.GetString("AutoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AutoRestarting Enabled.
        /// </summary>
        public static string AutoRestartActivated {
            get {
                return ResourceManager.GetString("AutoRestartActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AutoRestarting Disabled.
        /// </summary>
        public static string AutoRestartDeactivated {
            get {
                return ResourceManager.GetString("AutoRestartDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clicking YES you will delete $CONTENT$ and Stop related process.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure?.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error when adding new process.
        /// </summary>
        public static string ProcessAddedFail {
            get {
                return ResourceManager.GetString("ProcessAddedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Path $CONTENT$ cannot be added to processes.
        /// </summary>
        public static string ProcessAddedFailMessage {
            get {
                return ResourceManager.GetString("ProcessAddedFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ has been added.
        /// </summary>
        public static string ProcessAddedLog {
            get {
                return ResourceManager.GetString("ProcessAddedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Path $CONTENT$ added to processes.
        /// </summary>
        public static string ProcessAddedMessage {
            get {
                return ResourceManager.GetString("ProcessAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Added new process.
        /// </summary>
        public static string ProcessAddedSuccess {
            get {
                return ResourceManager.GetString("ProcessAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process stopped manually.
        /// </summary>
        public static string ProcessManuallyStopped {
            get {
                return ResourceManager.GetString("ProcessManuallyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ has been stopped manually.
        /// </summary>
        public static string ProcessManuallyStoppedLog {
            get {
                return ResourceManager.GetString("ProcessManuallyStoppedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ has been stopped and removed.
        /// </summary>
        public static string ProcessRemovedLog {
            get {
                return ResourceManager.GetString("ProcessRemovedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ has been restarted.
        /// </summary>
        public static string ProcessRestartedLog {
            get {
                return ResourceManager.GetString("ProcessRestartedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ is restarting.
        /// </summary>
        public static string ProcessRestartingLog {
            get {
                return ResourceManager.GetString("ProcessRestartingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process started.
        /// </summary>
        public static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ has been started.
        /// </summary>
        public static string ProcessStartedLog {
            get {
                return ResourceManager.GetString("ProcessStartedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process stopped.
        /// </summary>
        public static string ProcessStopped {
            get {
                return ResourceManager.GetString("ProcessStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ has been stopped.
        /// </summary>
        public static string ProcessStoppedLog {
            get {
                return ResourceManager.GetString("ProcessStoppedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Process $CONTENT$ has been updated.
        /// </summary>
        public static string ProcessUpdatedLog {
            get {
                return ResourceManager.GetString("ProcessUpdatedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Group Key for $CONTENT$.
        /// </summary>
        public static string SetGroupKeyMessage {
            get {
                return ResourceManager.GetString("SetGroupKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set Group Key.
        /// </summary>
        public static string SetGroupKeyTitle {
            get {
                return ResourceManager.GetString("SetGroupKeyTitle", resourceCulture);
            }
        }
    }
}
